[tasks.build-aarch64]
command = "cross"
args = ["build", "--release", "--target", "aarch64-unknown-linux-gnu"]

[tasks.upload-vps]
dependencies = ["build-aarch64"]
script = '''
ssh shaybox@vps "systemctl --user stop hex"
scp target/aarch64-unknown-linux-gnu/release/hex shaybox@vps:/home/shaybox/.cargo/bin/hex
ssh shaybox@vps "systemctl --user start hex"
'''